# Generated by Django 5.2.3 on 2026-05-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings',
         '0003_rename_photo_1_listing_photo_remove_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/listing/%id/'),
        ),
    ]
